

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:~/fiapcard/fiapcard;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    user:
      name: admin
      password: fiap
      roles: ADMIN


file:  
  path: /Users/zanchetta/fiapcard/alunos.txt
  input: classpath:alunos.txt
  